#!/usr/bin/env python3
"""Regenerate languages/en.ini from the launcher sources: every
L.T/L.F("key", "English") , Tr(control, "key", "English") and
AddLabel("key", "English", ...) call.  Other language files use the
same keys; tools/gen-lang-en.py --check lists keys missing in them."""
import collections, glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CALL = re.compile(r'(?:L\.[TF]\(|Tr\(\s*\w+\s*,|AddLabel\()\s*"([\w.]+)"\s*,\s*'
                  r'((?:"(?:[^"\\]|\\.)*"\s*\+?\s*)+)')
keys = collections.OrderedDict()
for f in sorted(glob.glob(os.path.join(ROOT, "windows", "*.cs"))):
    for m in CALL.finditer(open(f, encoding="utf-8").read()):
        lits = re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(2))
        v = "".join(lits).replace('\\"', '"').replace("\\\\", "\\")
        if keys.get(m.group(1), v) != v:
            sys.exit(f"key {m.group(1)}: two different English texts")
        keys[m.group(1)] = v

if "--check" in sys.argv:
    for f in sorted(glob.glob(os.path.join(ROOT, "languages", "*.ini"))):
        have = set(re.findall(r'^([\w.]+)=', open(f, encoding="utf-8").read(), re.M))
        miss = [k for k in keys if k not in have]
        print(f"{os.path.basename(f)}: {len(miss)} missing" + "".join("\n  " + k for k in miss))
    sys.exit(0)

out = ["; MT7981 Router Emulator - user interface texts (English).",
       "; To add a language: copy this file (e.g. de.ini), set name= and translate",
       "; the values. Missing keys fall back to English. \\n = new line,",
       "; {0}, {1} = values filled in by the program; keep them.",
       "; Generated by tools/gen-lang-en.py from windows/*.cs.",
       "[language]", "name=English", "", "[strings]"]
out += [f"{k}={v}" for k, v in keys.items()]
open(os.path.join(ROOT, "languages", "en.ini"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"{len(keys)} keys")
