#!/usr/bin/env python3
"""Generate default read values for DRAMC/DDRPHY NAO (status) registers
from MediaTek register headers (coreboot vendorcode mt8195, same IP family
as MT7981).  Status/"done" style fields read as 1, everything else 0."""
import re, sys
inc = sys.argv[1]
good = re.compile(r"(EMPTY|IDLE_STATUS|RESPONSE|_DONE|DONE$|RDY|READY|_OK$|_ACK|CPT$|_CPT|FINISH|COMPLETE|LOCK|_PASS)")
bad = re.compile(r'(ERR|FAIL|BUSY|FLAG|CNT|TIMEOUT|LATCH|OVERFLOW)')
out = []
for fname, block in (("8195_Register_DRAMC_NAO.h", "DRAMC_NAO"),
                     ("8195_Register_DDRPHY_NAO.h", "DDRPHY_NAO")):
    regs = {}
    cur = None
    for line in open(f"{inc}/{fname}"):
        m = re.match(r'#define (\w+)\s+\(\w+_BASE_ADDRESS \+ (0x[0-9A-Fa-f]+)\)', line)
        if m:
            cur = (m.group(1), int(m.group(2), 16)); regs[cur[1]] = [cur[0], 0]; continue
        m = re.match(r'\s+#define (\w+)\s+Fld\((\d+), (\d+)\)', line)
        if m and cur:
            name, w, sh = m.group(1), int(m.group(2)), int(m.group(3))
            if good.search(name) and not bad.search(name):
                regs[cur[1]][1] |= ((1 << w) - 1) << sh
    for off, (name, val) in sorted(regs.items()):
        if val:
            out.append((block, off, val, name))
print("/* generated by tools/gen_dramc_table.py - do not edit */")
print("static const struct { uint8_t blk; uint16_t off; uint32_t val; } dramc_nao_defaults[] = {")
for blk, off, val, name in out:
    print(f"    {{ {0 if blk=='DRAMC_NAO' else 1}, 0x{off:04x}, 0x{val:08x} }}, /* {name} */")
print("};")
